// Generated by dts-bundle-generator v6.0.0

export declare const EQUALITY_KEY: unique symbol;
export declare type IsEqualOptions = {
	ignoreKeys?: {
		[key: string]: boolean;
	};
	keyComparators?: {
		[key: string]: (a: any, b: any) => boolean;
	};
	log?: boolean;
	maxDepth?: number;
};
export declare function isEqual(a: any, b: any, options?: IsEqualOptions): boolean;

export {};
