#!/bin/bash
set -e

if [ "$STORMPROXY_HOSTS" = "" ]; then
    echo "missing env"
    exit 1
fi

flyctl secrets set \
    STORMPROXY_HOSTS="$STORMPROXY_HOSTS" \
    LUMINATI_PROXY_HOST="$LUMINATI_PROXY_HOST" \
    LUMINATI_PROXY_PORT="$LUMINATI_PROXY_PORT" \
    LUMINATI_PROXY_RESIDENTIAL_USER="$LUMINATI_PROXY_RESIDENTIAL_USER" \
    LUMINATI_PROXY_RESIDENTIAL_PASSWORD="$LUMINATI_PROXY_RESIDENTIAL_PASSWORD" \
    || true
