version: '3.7'

services:
  ci:
    image: registry.dishapp.com/dish-ci${DISH_IMAGE_TAG}
    command: start --spawn 6 --token ${BUILDITE_AGENT_TOKEN}
    build:
      context: ./services/ci
    volumes:
      - /var/lib/buildkite/builds:/var/lib/buildkite/builds
      - /usr/bin/buildkite-agent:/usr/local/bin/buildkite-agent
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/keys:/buildkite-secrets:ro
    environment:
      DISH_KEYS_PATH: /buildkite-secrets
      BUILDKITE_BUILD_PATH: /var/lib/buildkite/builds
      BUILDITE_AGENT_TOKEN: ${BUILDITE_AGENT_TOKEN}
      TRAEFIK_USERNAME: ${TRAEFIK_USERNAME}
      TRAEFIK_PASSWORD_PLAIN: ${TRAEFIK_PASSWORD_PLAIN}
