version: '3.7'

services:
  base:
    image: registry.dishapp.com/dish-base${DISH_IMAGE_TAG}
    build:
      context: .
      dockerfile: ./Dockerfile    

  run-tests:
    image: registry.dishapp.com/dish-run-tests${DISH_IMAGE_TAG}
    build:
      context: .
      dockerfile: ./services/run-tests/Dockerfile
