#!/bin/bash

if [ "$KEEP_ALIVE" != "true" ]; then
  set -e
fi

if command -v git &> /dev/null; then
  export DEV_USER=$(git config user.email | tr -d "[:space:]")
fi

if command -v ipconfig &> /dev/null; then
  LOCAL_HOST=$(ipconfig getifaddr en0)
fi

if [ "$DEV_USER" = "tom@tombh.co.uk" ]; then
  DISH_DEBUG=${DISH_DEBUG:-"0"}
fi

if [ "$DEV_USER" = "natewienert@gmail.com" ]; then
  DISH_DEBUG=${DISH_DEBUG:-"2"}
fi

CWD_DIR=$(pwd)
DISH_ENV="${DISH_ENV:-production}"
ENV_FILE=".env.$DISH_ENV"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
export LOCAL_HOST=${LOCALHOST:-"localhost"}
export PROJECT_ROOT=$SCRIPT_DIR
export DOCKER_CONFIG="$PROJECT_ROOT/etc/docker"

cd "$PROJECT_ROOT"

deps="etc/dsh_ctl_sh_deps"
source "$deps/utils.sh"
source "$deps/compose.sh"
source "$deps/deploy.sh"
source "$deps/ops.sh"
source "$deps/crawlers.sh"
source "$deps/setup.sh"
source "$deps/backups.sh"
source "$deps/ci.sh"
source "$deps/dev.sh"
source "$deps/dbs.sh"

# export DOCKER_TAG_NAMESPACE=${branch//\//-}
# export BASE_IMAGE=$DISH_REGISTRY/base:$DOCKER_TAG_NAMESPACE
pushd $PROJECT_ROOT >/dev/null
source_env
popd >/dev/null

function_to_run=$1

if [ "$DISH_DEBUG" -gt "0" ]; then
  echo "dsh -- env $DISH_ENV in $PROJECT_ROOT running $function_to_run $GIT_COMMIT"
fi

if [ "$NO_PRINT_HELP" != "1" ] && [ "$function_to_run" = "" ]; then
  for f in $(declare -F | cut -d ' ' -f3); do
    echo "${f}"
  done
  exit 0
fi

shift
ORIGINAL_ARGS="$@"
$function_to_run "$@"

# Kills all child process, ampersanded things like `long_running_daemon.sh &`
trap terminate SIGINT
terminate(){
  pkill -SIGINT -P $$
  exit
}

if [ "$KEEP_ALIVE" = "true" ]; then
  tail -f dsh
fi
