CREATE INDEX IF NOT EXISTS dish_name_trgm_idx ON public.menu_item USING gin (name public.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS hrr_wkb_geometry_geom_idx ON public.hrr USING gist (wkb_geometry);
CREATE INDEX IF NOT EXISTS menu_item_description_trgm_idx ON public.menu_item USING gin (description public.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS menu_item_restaurant_id_idx ON public.menu_item USING btree (restaurant_id);
CREATE INDEX IF NOT EXISTS opening_hours_restaurant_id_idx ON public.opening_hours USING btree (restaurant_id);
CREATE INDEX IF NOT EXISTS opening_hours_spgist_idx ON public.opening_hours USING spgist (hours);
CREATE INDEX IF NOT EXISTS photo_xref_photo_id_idx ON public.photo_xref USING btree (photo_id);
CREATE INDEX IF NOT EXISTS photo_xref_restaurant_id_idx ON public.photo_xref USING btree (restaurant_id);
CREATE INDEX IF NOT EXISTS restaurant_id_ordered_index ON public.restaurant USING btree (id);
CREATE INDEX IF NOT EXISTS restaurant_rating_index ON public.restaurant USING btree (rating DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS restaurant_sources_index ON public.restaurant USING gin (sources jsonb_path_ops);
CREATE INDEX IF NOT EXISTS restaurant_tag_names_trgm_idx ON public.restaurant USING gin (tag_names);
CREATE INDEX IF NOT EXISTS restaurant_tag_restaurant_id_idx ON public.restaurant_tag USING btree (restaurant_id);
CREATE INDEX IF NOT EXISTS restaurant_trgm_idx ON public.restaurant USING gin (name public.gin_trgm_ops);
CREATE UNIQUE INDEX IF NOT EXISTS review_native_data_unique_constraint ON public.review USING btree (user_id, restaurant_id, tag_id) WHERE (user_id <> '00000000-0000-0000-0000-000000000001'::uuid);
CREATE INDEX IF NOT EXISTS review_newest_idx ON public.review USING btree (restaurant_id, authored_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS review_restaurant_id_idx ON public.review USING btree (restaurant_id);
CREATE INDEX IF NOT EXISTS review_tag_review_id_idx ON public.review_tag_sentence USING btree (review_id);
CREATE INDEX IF NOT EXISTS review_text_gin_trgm_idx ON public.review USING gin (text public.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS review_user_id_idx ON public.review USING btree (user_id);
CREATE INDEX IF NOT EXISTS review_username_idx ON public.review USING btree (username);
CREATE INDEX IF NOT EXISTS tag_alternates_gin_idx ON public.tag USING gin (alternates);
CREATE INDEX IF NOT EXISTS tag_name_idx ON public.tag USING btree (name);
CREATE INDEX IF NOT EXISTS zcta5_wkb_geometry_geom_idx ON public.zcta5 USING gist (wkb_geometry);
