steps:
  - label: ":docker: Build base"
    plugins:
      - seek-oss/docker-ecr-cache#v1.9.0:
          registry-provider: gcr
          gcp-project: dish-258800
          cache-on:
            - yarn.lock
            - '**/package.json'
      - docker#v3.3.0:
          volumes:
            - /app/node_modules
      - docker-compose#v3.7.0:
          build:
            - base
          image-repository: gcr.io/dish-258800/base
          push: base:gcr.io/dish-258800/base:latest

  - wait

  - label: ":docker: Build apps"
    plugins:
      - seek-oss/docker-ecr-cache#v1.9.0:
          registry-provider: gcr
          gcp-project: dish-258800
          cache-on:
            - yarn.lock
            - '**/package.json'
      - docker#v3.3.0:
          volumes:
            - /app/node_modules
      - docker-compose#v3.7.0:
          build:
            - dish-hooks
            - dish-app-web
            - search
          push:
            - dish-hooks:gcr.io/dish-258800/dish-hooks:latest
            - dish-app-web:gcr.io/dish-258800/dish-app-web:latest
            - search:gcr.io/dish-258800/search:latest

  - wait

  - label: "run tests"
    command: "docker run --net host $DISH_REGISTRY/base yarn test"
    plugins:
      - seek-oss/docker-ecr-cache#v1.9.0:
          registry-provider: gcr
          gcp-project: dish-258800
      - docker-compose#v3.7.0:
          run: dish-app-web
