steps:
  - label: "Build images and test"
    command: ".github/workflows/scripts/setup_services.sh"
    plugins:
      - seek-oss/docker-ecr-cache#v1.9.0:
          registry-provider: gcr
          gcp-project: dish-258800
          cache-on:
            - yarn.lock
            - '**/package.json'
      - docker#v3.3.0:
          volumes:
            - /app/node_modules
      - docker-compose#v3.7.0:
          build: base
          image-repository: gcr.io/dish-258800/base
