env:
  DISH_ENV: 'test'
  DISH_REGISTRY: 'gcr.io/dish-258800'
  HASURA_ENDPOINT: 'http://localhost:8080'
  DISH_ENDPOINT: 'http://localhost:4444'

steps:
  - label: ":docker: build base & non-base dependent images"
    command: "echo go"
    env:
      IGNORE_SETUP: true

  - label: ":docker: build base"
    plugins:
      - gencer/cache#v2.3.10:
          backend: s3
          key: "v1-cache-{{ runner.os }}-base-yarn"
          s3:
            args: "--endpoint-url=https://sfo2.digitaloceanspaces.com"
            bucket: "dish-build-cache"
          paths:
            - './data/'
      - docker-compose#v3.7.0:
          build:
            - base
          image-repository: gcr.io/dish-258800/base
          cache-from: base:gcr.io/dish-258800/base:latest
          push: base:gcr.io/dish-258800/base:latest
          volumes:
            - "./dist:/app/dist"
            - "./data:/data"
            - "./data/node_modules:/app/node_modules"
            - "./data/dish-app/node_modules:/app/dish-app/node_modules"

  - label: ":docker: build search"
    plugins:
      - docker-compose#v3.7.0:
          build: search
          image-repository: gcr.io/dish-258800/search
          cache-from: base:gcr.io/dish-258800/search:latest
          push: search:gcr.io/dish-258800/search:latest

  - label: ":docker: build hasura"
    plugins:
      - docker-compose#v3.7.0:
          build: hasura
          image-repository: gcr.io/dish-258800/hasura
          cache-from: base:gcr.io/dish-258800/hasura:latest
          push: hasura:gcr.io/dish-258800/hasura:latest

  - label: ":docker: build timescale"
    plugins:
      - docker-compose#v3.7.0:
          build: timescaledb
          image-repository: gcr.io/dish-258800/timescaledb
          cache-from: base:gcr.io/dish-258800/timescaledb:latest
          push: timescaledb:gcr.io/dish-258800/timescaledb:latest

  - label: ":docker: build tileserver"
    plugins:
      - docker-compose#v3.7.0:
          build: tileserver
          image-repository: gcr.io/dish-258800/tileserver
          cache-from: base:gcr.io/dish-258800/tileserver:latest
          push: tileserver:gcr.io/dish-258800/tileserver:latest

  - label: ":docker: build image-proxy"
    plugins:
      - docker-compose#v3.7.0:
          build: image-proxy
          image-repository: gcr.io/dish-258800/image-proxy
          cache-from: base:gcr.io/dish-258800/image-proxy:latest
          push: image-proxy:gcr.io/dish-258800/image-proxy:latest

  - wait

  - label: ":docker: base-dependent images"
    command: "echo ok"
    env:
      IGNORE_SETUP: true

  - label: ":docker: build dish-hooks"
    plugins:
      - docker-compose#v3.7.0:
          build: dish-hooks
          image-repository: gcr.io/dish-258800/dish-hooks
          cache-from: base:gcr.io/dish-258800/dish-hooks:latest
          push: dish-hooks:gcr.io/dish-258800/dish-hooks:latest

  - label: ":docker: build dish-app-web"
    plugins:
      - docker-compose#v3.7.0:
          build: dish-app-web
          image-repository: gcr.io/dish-258800/dish-app-web
          cache-from: base:gcr.io/dish-258800/dish-app-web:latest
          push: dish-app-web:gcr.io/dish-258800/dish-app-web:latest

  - label: ":docker: build worker"
    plugins:
      - docker-compose#v3.7.0:
          build: worker
          image-repository: gcr.io/dish-258800/worker
          cache-from: base:gcr.io/dish-258800/worker:latest
          push: worker:gcr.io/dish-258800/worker:latest

  - label: ":docker: build postgres for testing"
    plugins:
      - docker-compose#v3.7.0:
          build: postgres
          image-repository: gcr.io/dish-258800/postgres
          cache-from: base:gcr.io/dish-258800/postgres:latest
          push: postgres:gcr.io/dish-258800/postgres:latest
          env:
            POSTGRES_STRATEGY: simple

  - wait

  - label: "setup services for tests"
    command: ".buildkite/scripts/setup_services.sh"
    env:
      LOG_DOCKER: true
    plugins:
      - gencer/cache#v2.3.10:
          backend: s3
          key: "v1-cache-{{ runner.os }}-{{ checksum 'services/hasura/package.json' }}"
          s3:
            args: "--endpoint-url=https://sfo2.digitaloceanspaces.com"
            bucket: "dish-build-cache"
          paths:
            - '/root/.dish/'

  - wait

  - label: "run tests"
    command: "docker run --net host ${DISH_REGISTRY}/base yarn test"
    env:
      LOG_DOCKER: true

  # - label: "run integration test"
  #   command: ".buildkite/scripts/integration_tests.sh"

  - wait

  - label: "deploy"
    env:
      DOCKER_CLEAN: true
    command: ".buildkite/scripts/deploy_all.sh"

  - wait

  - label: "finish"
    command: "echo done"
    env:
      DOCKER_CLEAN: true
