env:
  BUILDKITE_TIMEOUT: "40"
  DISH_IMAGE_TAG: ":latest"
  DISH_ENV: 'test'
  DISH_REGISTRY: 'gcr.io/dish-258800'
  HASURA_ENDPOINT: 'http://localhost:8080'
  DISH_ENDPOINT: 'http://localhost:4444'

steps:
  # images that tests need

  - label: ":docker: build base"
    key: base
    plugins:
      - docker-compose#v3.7.0:
          build: base
          cache-from: base:gcr.io/dish-258800/base:latest
          image-repository: gcr.io/dish-258800/base
          push: base:gcr.io/dish-258800/base:latest

  - label: ":docker: build dish-app"
    env:
      DOCKER_TAG: true
    key: dish-app
    depends_on: base
    plugins:
      - docker-compose#v3.7.0:
          build: dish-app
          cache-from: base:gcr.io/dish-258800/dish-app:latest

  - label: ":docker: build run-tests"
    key: run-tests
    env:
      DOCKER_TAG: true
    depends_on: base
    plugins:
      - docker-compose#v3.7.0:
          build: run-tests
          cache-from: base:gcr.io/dish-258800/run-tests:latest

  - label: ":docker: build hooks"
    env:
      DOCKER_TAG: true
    key: hooks
    depends_on: base
    plugins:
      - docker-compose#v3.7.0:
          build: hooks
          cache-from: base:gcr.io/dish-258800/hooks:latest

  - label: ":docker: build worker"
    key: worker
    env:
      DOCKER_TAG: true
    depends_on: base
    plugins:
      - docker-compose#v3.7.0:
          build: worker
          cache-from: base:gcr.io/dish-258800/worker:latest

  - label: ":docker: build search"
    key: search
    env:
      DOCKER_TAG: true
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: search
          cache-from: base:gcr.io/dish-258800/search:latest

  - label: ":docker: build hasura"
    key: hasura
    env:
      DOCKER_TAG: true
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: hasura
          cache-from: base:gcr.io/dish-258800/hasura:latest

  - label: ":docker: build timescale"
    key: timescale
    env:
      DOCKER_TAG: true
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: timescale
          cache-from: base:gcr.io/dish-258800/timescale:latest

  - label: ":docker: build tileserver"
    key: tileserver
    env:
      DOCKER_TAG: true
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: tileserver
          cache-from: base:gcr.io/dish-258800/tileserver:latest

  - label: ":docker: build postgres for tests"
    key: postgres
    env:
      DOCKER_TAG: true
    retry:
      automatic: true
    env:
      POSTGRES_NAME: postgres
    plugins:
      - docker-compose#v3.7.0:
          build: postgres
          cache-from: base:gcr.io/dish-258800/postgres:latest

  - label: ":docker: build redis for tests"
    key: redis
    env:
      DOCKER_TAG: true
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: redis
          cache-from: base:gcr.io/dish-258800/redis:latest

  - label: "done with test images"
    command: "true"
    key: test-images
    depends_on:
      - dish-app
      - hooks
      - worker
      - search
      - hasura
      - timescale
      - tileserver
      - run-tests
      - postgres
      - redis

  - label: "push pre-test images to fly"
    depends_on: test-images
    plugins:
      - docker-compose#v3.7.0:
          push:
            - dish-app:registry.fly.io/dish-app:latest
            - hooks:registry.fly.io/dish-hooks:latest
            - worker:registry.fly.io/dish-worker:latest
            - search:registry.fly.io/dish-search:latest
            - hasura:registry.fly.io/dish-hasura:latest
            - timescale:registry.fly.io/dish-timescale:latest
            - tileserver:registry.fly.io/dish-tileserver:latest
            - tileserver:registry.fly.io/dish-tileserver:latest

  - label: "push pre-test images to gcr"
    depends_on: test-images
    plugins:
      - docker-compose#v3.7.0:
          push:
          - dish-app:gcr.io/dish-258800/dish-app:latest
          - run-tests:gcr.io/dish-258800/run-tests:latest
          - hooks:gcr.io/dish-258800/hooks:latest
          - worker:gcr.io/dish-258800/worker:latest
          - search:gcr.io/dish-258800/search:latest
          - hasura:gcr.io/dish-258800/hasura:latest
          - timescale:gcr.io/dish-258800/timescale:latest
          - tileserver:gcr.io/dish-258800/tileserver:latest
          - postgres:gcr.io/dish-258800/postgres:latest
          - redis:gcr.io/dish-258800/redis:latest

  # non test images

  - label: ":docker: build cron"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: cron
          image-repository: gcr.io/dish-258800/cron
          cache-from: base:gcr.io/dish-258800/cron:latest
          push:
            - cron:gcr.io/dish-258800/cron:latest
            - cron:registry.fly.io/dish-cron:latest

  - label: ":docker: build gorse"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: gorse
          image-repository: gcr.io/dish-258800/gorse
          cache-from: base:gcr.io/dish-258800/gorse:latest
          push:
            - gorse:gcr.io/dish-258800/gorse:latest
            - gorse:registry.fly.io/dish-gorse:latest

  - label: ":docker: build bert"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: bert
          image-repository: gcr.io/dish-258800/bert
          cache-from: base:gcr.io/dish-258800/bert:latest
          push:
            - bert:gcr.io/dish-258800/bert:latest
            - bert:registry.fly.io/dish-bert:latest

  - label: ":docker: build image-proxy"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: image-proxy
          image-repository: gcr.io/dish-258800/image-proxy
          cache-from: base:gcr.io/dish-258800/image-proxy:latest
          push:
            - image-proxy:gcr.io/dish-258800/image-proxy:latest
            - image-proxy:registry.fly.io/dish-image-proxy:latest

  - label: ":docker: build image-quality"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: image-quality
          image-repository: gcr.io/dish-258800/image-quality
          cache-from: base:gcr.io/dish-258800/image-quality:latest
          push:
            - image-quality:gcr.io/dish-258800/image-quality:latest
            - image-quality:registry.fly.io/dish-image-quality:latest

  - label: ":docker: build db"
    retry:
      automatic: true
    env:
      POSTGRES_NAME: db
    plugins:
      - docker-compose#v3.7.0:
          build: postgres
          image-repository: gcr.io/dish-258800/db
          cache-from: base:gcr.io/dish-258800/db:latest
          push:
            - postgres:gcr.io/dish-258800/db:latest
            - postgres:gcr.io/dish-258800/dish-db:latest

  - label: "setup services for tests"
    if: build.branch != "master"
    key: test-setup
    command: ".buildkite/scripts/setup_services.sh"
    depends_on:
      - test-images
    env:
      LOG_DOCKER: true
      IS_COMPOSE_RUNNER: true
      DOCKER_CLEAN_ON_FAIL: true
      POSTGRES_STRATEGY: simple
    plugins:
      - gencer/cache#v2.3.10:
          backend: s3
          key: "v1-cache-{{ runner.os }}"
          s3:
            args: "--endpoint-url=https://sfo2.digitaloceanspaces.com"
            bucket: "dish-build-cache"
          paths:
            - '/root/.dish/'

  - label: "run tests"
    if: build.branch != "master"
    key: tests
    command: "docker run --net host gcr.io/dish-258800/run-tests:latest yarn test"
    depends_on: test-setup
    env:
      LOG_DOCKER: true
      DOCKER_CLEAN_ON_FAIL: true

  # - label: "run integration test"
  #   command: ".buildkite/scripts/integration_tests.sh"

  - wait

  - label: "deploy"
    # if: build.branch == "production"
    command: ".buildkite/scripts/deploy_all.sh"
    artifact_paths:
      - "*.log"
    env:
      DOCKER_CLEAN: true

  - wait

  - label: "finish"
    command: ".buildkite/scripts/finish.sh"
    env:
      FINISH: true
