env:
  DISH_ENV: 'test'
  DISH_REGISTRY: 'gcr.io/dish-258800'
  HASURA_ENDPOINT: 'http://localhost:8080'
  DISH_ENDPOINT: 'http://localhost:4444'

steps:
  - label: ":docker: build base"
    env:
      LOG_DOCKER: true
    plugins:
      - docker-compose#v3.7.0:
          build:
            - base
          image-repository: gcr.io/dish-258800/base
          cache-from: base:gcr.io/dish-258800/base:latest
          push: base:gcr.io/dish-258800/base:latest
          volumes:
            - "./dist:/app/dist"

  - wait

  - label: ":docker: build apps"
    env:
      LOG_DOCKER: true
    plugins:
      - docker-compose#v3.7.0:
          build-parallel: true
          build:
            - dish-hooks
            - dish-app-web
            - search
          push:
            - dish-hooks:gcr.io/dish-258800/dish-hooks:latest
            - dish-app-web:gcr.io/dish-258800/dish-app-web:latest
            - search:gcr.io/dish-258800/search:latest

  - wait

  - label: "setup services for tests"
    command: ".buildkite/scripts/setup_services.sh"
    plugins:
      - gencer/cache#v2.3.10:
          backend: s3
          key: "v1-cache-{{ runner.os }}-{{ checksum 'services/hasura/package.json' }}"
          s3:
            args: "--endpoint-url=https://sfo2.digitaloceanspaces.com"
            bucket: "dish-build-cache"
          paths:
            - '/root/.dish/'

  - wait

  - label: "run tests"
    command: "docker run --net host ${DISH_REGISTRY}/base yarn test"

  - label: "run integration test"
    command: ".buildkite/scripts/integration_tests.sh"

  - wait

  - label: "deploy to staging"
    env:
      DOCKER_CLEAN: true
    command: ".buildkite/scripts/deploy_all.sh"

  - wait

  - label: "finish"
    command: "echo done"
    env:
      DOCKER_CLEAN: true
