env:
  DISH_BASE_VERION: ":latest"
  DISH_IMAGE_TAG: ":latest"
  DISH_ENV: 'test'
  DISH_REGISTRY: 'gcr.io/dish-258800'
  HASURA_ENDPOINT: 'http://localhost:8080'
  DISH_ENDPOINT: 'http://localhost:4444'

steps:
  - label: ":docker: build base"
    key: base
    plugins:
      - docker-compose#v3.7.0:
          build: base
          image-repository: gcr.io/dish-258800/base
          cache-from: base:gcr.io/dish-258800/base:latest
          push: base:gcr.io/dish-258800/base:latest

  - label: ":docker: build dish-app"
    depends_on: base
    key: web
    plugins:
      - docker-compose#v3.7.0:
          build: dish-app
          image-repository: gcr.io/dish-258800/dish-app
          cache-from: base:gcr.io/dish-258800/dish-app:latest
          push: dish-app:gcr.io/dish-258800/dish-app:latest

  - label: ":docker: build run-tests"
    depends_on: base
    plugins:
      - docker-compose#v3.7.0:
          build:
            - run-tests
            - worker
            - hooks
          image-repository: gcr.io/dish-258800
          cache-from: base:gcr.io/dish-258800:latest
          push: run-tests:gcr.io/dish-258800:latest

  - label: ":docker: build search"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: search
          image-repository: gcr.io/dish-258800/search
          cache-from: base:gcr.io/dish-258800/search:latest
          push: search:gcr.io/dish-258800/search:latest

  - label: ":docker: build hasura"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: hasura
          image-repository: gcr.io/dish-258800/hasura
          cache-from: base:gcr.io/dish-258800/hasura:latest
          push: hasura:gcr.io/dish-258800/hasura:latest

  - label: ":docker: build timescaledb"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: timescaledb
          image-repository: gcr.io/dish-258800/timescaledb
          cache-from: base:gcr.io/dish-258800/timescaledb:latest
          push: timescaledb:gcr.io/dish-258800/timescaledb:latest

  - label: ":docker: build tileserver"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: tileserver
          image-repository: gcr.io/dish-258800/tileserver
          cache-from: base:gcr.io/dish-258800/tileserver:latest
          push: tileserver:gcr.io/dish-258800/tileserver:latest

  - label: ":docker: build image-proxy"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: image-proxy
          image-repository: gcr.io/dish-258800/image-proxy
          cache-from: base:gcr.io/dish-258800/image-proxy:latest
          push: image-proxy:gcr.io/dish-258800/image-proxy:latest

  - label: ":docker: build image-quality"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: image-quality
          image-repository: gcr.io/dish-258800/image-quality
          cache-from: base:gcr.io/dish-258800/image-quality:latest
          push: image-quality:gcr.io/dish-258800/image-quality:latest

  - label: ":docker: run-tests"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: run-tests
          image-repository: gcr.io/dish-258800/run-tests
          cache-from: base:gcr.io/dish-258800/run-tests:latest
          push: run-tests:gcr.io/dish-258800/run-tests:latest

  - label: ":docker: build postgres for tests"
    retry:
      automatic: true
    env:
      POSTGRES_NAME: postgres
    plugins:
      - docker-compose#v3.7.0:
          build: postgres
          image-repository: gcr.io/dish-258800/postgres
          cache-from: base:gcr.io/dish-258800/postgres:latest
          push: postgres:gcr.io/dish-258800/postgres:latest

  - label: ":docker: build redis for tests"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: redis
          image-repository: gcr.io/dish-258800/redis
          cache-from: base:gcr.io/dish-258800/redis:latest
          push: redis:gcr.io/dish-258800/redis:latest

  - label: ":docker: build gorse"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: gorse
          image-repository: gcr.io/dish-258800/gorse
          cache-from: base:gcr.io/dish-258800/gorse:latest
          push: gorse:gcr.io/dish-258800/gorse:latest

  - label: ":docker: build bert"
    retry:
      automatic: true
    plugins:
      - docker-compose#v3.7.0:
          build: bert
          image-repository: gcr.io/dish-258800/bert
          cache-from: base:gcr.io/dish-258800/bert:latest
          push: bert:gcr.io/dish-258800/bert:latest

  - wait

  - label: ":docker: build db"
    key: db
    retry:
      automatic: true
    env:
      POSTGRES_NAME: db
    plugins:
      - docker-compose#v3.7.0:
          build: postgres
          image-repository: gcr.io/dish-258800/db
          cache-from: base:gcr.io/dish-258800/db:latest
          push: postgres:gcr.io/dish-258800/db:latest

  - label: "setup services for tests"
    command: ".buildkite/scripts/setup_services.sh"
    key: test-setup
    env:
      LOG_DOCKER: true
      DOCKER_CLEAN_ON_FAIL: true
      POSTGRES_STRATEGY: simple
    plugins:
      - gencer/cache#v2.3.10:
          backend: s3
          key: "v2-cache-{{ runner.os }}"
          s3:
            args: "--endpoint-url=https://sfo2.digitaloceanspaces.com"
            bucket: "dish-build-cache"
          paths:
            - '/root/.dish/'

  - label: "run tests"
    key: tests
    depends_on: test-setup
    command: "docker run --net host gcr.io/dish-258800/run-tests:latest yarn test"
    env:
      LOG_DOCKER: true
      DOCKER_CLEAN_ON_FAIL: true

  # - label: "run integration test"
  #   command: ".buildkite/scripts/integration_tests.sh"

  - label: "deploy"
    depends_on:
      - tests
      - db
    env:
      DOCKER_CLEAN: true
    command: ".buildkite/scripts/deploy_all.sh"

  - wait

  - label: "finish"
    command: ".buildkite/scripts/finish.sh"
    env:
      FINISH: true
