env:
  DISH_ENV: 'test'
  DISH_REGISTRY: 'gcr.io/dish-258800'
  HASURA_ENDPOINT: 'http://localhost:8080'
  DISH_ENDPOINT: 'http://localhost:4444'

steps:
  - label: ":docker: Build base"
    command: "echo done"
    plugins:
      - seek-oss/docker-ecr-cache#v1.9.0:
          registry-provider: gcr
          gcp-project: dish-258800
          cache-on:
            - yarn.lock
            - '**/package.json'
      - docker#v3.3.0:
          volumes:
            - /app/node_modules
      - docker-compose#v3.7.0:
          build:
            - base
          image-repository: gcr.io/dish-258800/base
          push: base:gcr.io/dish-258800/base:latest

  - wait

  - label: ":docker: Build apps"
    command: "echo done"
    plugins:
      - seek-oss/docker-ecr-cache#v1.9.0:
          registry-provider: gcr
          gcp-project: dish-258800
          cache-on:
            - yarn.lock
            - '**/package.json'
      - docker#v3.3.0:
          volumes:
            - /app/node_modules
      - docker-compose#v3.7.0:
          build:
            - dish-hooks
            - dish-app-web
            - search
            - worker
          push:
            - dish-hooks:gcr.io/dish-258800/dish-hooks:latest
            - dish-app-web:gcr.io/dish-258800/dish-app-web:latest
            - search:gcr.io/dish-258800/search:latest
            - worker:gcr.io/dish-258800/worker:latest

  - wait

  - label: "run tests"
    command: ".buildkite/scripts/setup_services.sh"
    plugins:
      - seek-oss/docker-ecr-cache#v1.9.0:
          registry-provider: gcr
          gcp-project: dish-258800
