-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQge4QykoYplDRqP7/i
izccklVEk/cQFJSfkb/f3zPb1CCgCgYIKoZIzj0DAQehRANCAAR8FzgIkNr1kflW
a2Mg3SPAuHqpcWo5suPv7j+/88N5IozEyHU7yeHQx8CjwJma+eiDV/5XirzV7Zgs
62GuhGl1
-----END PRIVATE KEY-----