#!/bin/bash

set -euo pipefail

GITHUB_SSH_KEY=$(cat /buildkite-secrets/d1_reliablesite_dish)

eval "$(ssh-agent -s)"
ssh-add - <<< "$GITHUB_SSH_KEY"

if ($(which git-crypt > /dev/null)); then
  echo "git crypt installed"
else
  apt-get install -y git-crypt
fi
