# This section declares settings for the server.
[server]
host = "0.0.0.0"        # server host
port = 9000             # server port

# This section declares setting for the database.
[database]
file = "/data/gorse.db"       # database file

# This section declares settings for recommendation.
[recommend]
model = "svd"           # recommendation model
cache_size = 100        # the number of cached recommendations
update_threshold = 2    # update model when more than n ratings are added
check_period = 1        # check for update every one minute
similarity = "pearson"  # similarity metric for neighbors

# This section declares hyperparameters for the recommendation model.
[params]
optimizer = "sgd"       # the optimizer to oprimize matrix factorization model
n_factors = 10          # the number of latent factors
reg = 0.01              # regularization strength
lr = 0.05               # learning rate
n_epochs = 100          # the number of learning epochs
init_mean = 0.01         # the mean of initial latent factors initilaized by Gaussian distribution
init_std = 0.001        # the standard deviation of initial latent factors initilaized by Gaussian distribution
