// Generated by dts-bundle-generator v6.1.0

export declare const sentryMessage: (message: string, { data, tags, logger, }?: {
	data?: any;
	tags?: {
		[key: string]: string;
	} | undefined;
	logger?: ((...args: any[]) => void) | undefined;
}) => void;
export declare const sentryException: (error: Error, { data, tags, logger, }?: {
	data?: any;
	tags?: {
		[key: string]: string;
	} | undefined;
	logger?: ((...args: any[]) => void) | undefined;
}) => void;

export {};
