import './_polyfill'
import { App } from './app/App'
import { homeStore } from './app/homeStore'
import { useUserStore, userStore } from './app/userStore'
import { showRadar } from './constants/constants'
import { getInitialHomeState } from './constants/initialHomeState'
import { tagDefaultAutocomplete, tagFilters, tagLenses } from './constants/localTags'
import './globals'
import { addTagsToCache } from './helpers/allTags'
import { DRoutesTable, router, routes } from './router'
import config from './tamagui.config'
import { createAuth, useHydrateCache } from '@dish/graph'
import { configureAssertHelpers } from '@dish/helpers'
import { ProvideRouter } from '@dish/router'
import { PortalProvider, TamaguiProvider, Toast, isWeb } from '@dish/ui'
import { Inter_400Regular, Inter_800ExtraBold } from '@expo-google-fonts/inter'
import { configureUseStore } from '@tamagui/use-store'
import * as Font from 'expo-font'
import * as SplashScreen from 'expo-splash-screen'
import React, { Suspense, useEffect, useState } from 'react'
import { useColorScheme } from 'react-native'
