FROM h2non/imaginary

CMD ["-p", "8981", "-enable-url-source", "-http-read-timeout","6","-enable-placeholder", "-concurrency", "30"]

# todo get this and set it up for prometheus logging
# https://github.com/marcfrederick/imaginary-exporter

# CMD [ '-enable-url-source', , '-enable-placeholder' ]
