# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'new-dish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for new-dishi
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GoogleSignIn'
  # pod 'Firebase/Core'
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Auth'
  # pod 'Firebase/Firestore'
  # pod 'Firebase/Storage'

end
