# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'dish' do
  supports_swift_versions '>= 4.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # pod 'GoogleMaps'
  # pod 'GooglePlaces'
  # pod 'GoogleSignIn'
  pod 'XCGLogger', '~> 7.0.0'
  # pod 'Firebase/Core'
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Auth'
  # pod 'Firebase/Firestore'
  # pod 'Firebase/Storage'
  pod 'Introspect', :git => 'git@github.com:siteline/SwiftUI-Introspect.git'
  # pod 'Mapbox-iOS-SDK', '~> 5.6'
  # pod 'MapboxAnnotationExtension', '0.0.1-beta.1'

  # pod 'Hasura'
  pod 'Apollo'
  pod 'Apollo/WebSocket'
end
