require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
# is_arm = '/usr/sbin/sysctl -n hw.optional.arm64 2>&1'.to_i

target 'dish' do
  config = use_native_modules!
  $ReactNativeMapboxGLIOSVersion = '~> 6.3'
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  use_unimodules!
  use_flipper!

  # if is_arm == 1 then
  #   pod 'hermes-engine', :git => 'https://github.com/Arkkeeper/hermes.git'
  # else
  #   pod 'hermes-engine', '~> 0.7.2'
  # end
end

pre_install do |installer|
  $RNMBGL.pre_install(installer)
end

post_install do |installer|
  $RNMBGL.post_install(installer)

	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
		config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
		end
	end
end
