require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
platform :ios, '12.0'

target 'dish' do
  # faster mapbox on simulator
  $ReactNativeMapboxGLIOSVersion = '~> 6.3'
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  use_unimodules!
  use_flipper!
end
