require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
platform :ios, '11.0'

target 'dish' do
  # faster mapbox on simulator
  $ReactNativeMapboxGLIOSVersion = '~> 6.3'
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    # :hermes_enabled => false
  )
  use_unimodules!
  use_flipper!
end

post_install do |installer|
  # react_native_post_install(installer)

	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
		config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
		end
	end
end
