#!/usr/bin/env bash
set -e pipefail

export HASURA_GRAPHQL_NO_OF_RETRIES=20
export HASURA_GRAPHQL_DATABASE_URL=$HASURA_FLY_POSTGRES_URL
export HASURA_GRAPHQL_ENABLED_LOG_TYPES="startup, http-log, webhook-log, websocket-log, query-log"
export HASURA_GRAPHQL_ENABLE_TELEMETRY=false
export HASURA_GRAPHQL_ADMIN_SECRET=${TF_VAR_HASURA_GRAPHQL_ADMIN_SECRET:-password}
export HASURA_GRAPHQL_UNAUTHORIZED_ROLE="anon"
export HASURA_GRAPHQL_JWT_SECRET='{"type":"HS256", "key":"12345678901234567890123456789012"}'
export HASURA_GRAPHQL_ENABLE_CONSOLE=true
export DISH_HOOKS_ENDPOINT="http://dish-hooks:6154"
export GORSE_SYNC_HOOK="http://dish-hooks:6154/gorse_sync"
export VIRTUAL_HOST="dish-hasura.fly.dev"

flyctl secrets set \
    HASURA_GRAPHQL_NO_OF_RETRIES="$HASURA_GRAPHQL_NO_OF_RETRIES" \
    HASURA_GRAPHQL_DATABASE_URL="$HASURA_GRAPHQL_DATABASE_URL" \
    HASURA_GRAPHQL_ENABLED_LOG_TYPES="$HASURA_GRAPHQL_ENABLED_LOG_TYPES" \
    HASURA_GRAPHQL_ENABLE_TELEMETRY="$HASURA_GRAPHQL_ENABLE_TELEMETRY" \
    HASURA_GRAPHQL_ADMIN_SECRET="$HASURA_GRAPHQL_ADMIN_SECRET" \
    HASURA_GRAPHQL_UNAUTHORIZED_ROLE="$HASURA_GRAPHQL_UNAUTHORIZED_ROLE" \
    HASURA_GRAPHQL_JWT_SECRET="$HASURA_GRAPHQL_JWT_SECRET" \
    HASURA_GRAPHQL_ENABLE_CONSOLE="$HASURA_GRAPHQL_ENABLE_CONSOLE" \
    DISH_HOOKS_ENDPOINT="$DISH_HOOKS_ENDPOINT" \
    GORSE_SYNC_HOOK="$GORSE_SYNC_HOOK" \
    VIRTUAL_HOST="$VIRTUAL_HOST" || true
