#!/bin/bash

set -eo pipefail

if [ "$FIRST_STEP" == "true" ]; then
  exit 0
fi

if [ "$LOG_DOCKER" == "true" ]; then
  echo "docker logs..."
  docker-compose logs --tail 2000
  cat ./*.logs || true
fi

if [ "$BUILDKITE_COMMAND_EXIT_STATUS" = "1" ]; then
  echo "shutting down docker"
  docker-compose down --volumes || true
fi

if [ "$DOCKER_CLEAN" == "true" ] || { [ "$BUILDKITE_COMMAND_EXIT_STATUS" = "1" ] && [ "$BUILDKITE_COMMAND_EXIT_STATUS" = "1" ]; }; then
  docker system prune -a --filter "until=24h" --force || true
  # this may clear useful cache?
  # docker system df | head -n 60 || true
  docker images -a | head -n 60 || true
fi

echo "bye"
