#!/bin/bash

set -eo pipefail

if [ "$FIRST_STEP" == "true" ]; then
  exit 0
fi

if [ "$BUILDKITE_COMMAND_EXIT_STATUS" -ne 0 ]; then
  echo "Steps are skipped because $BUILDKITE_AGENT_NAME:$BUILDKITE_LABEL returned $BUILDKITE_COMMAND_EXIT_STATUS" > /opt/ci/inner/skip
fi

if [ "$DOCKER_COMPOSE_DOWN" == "true" ]; then
  docker-compose down &
fi

if [ -n "$DOCKER_TAG" ]; then
  from="$BUILDKITE_PIPELINE_NAME-$BUILDKITE_STEP_KEY-build-$BUILDKITE_BUILD_NUMBER:latest"
  to="registry.fly.io/dish-$BUILDKITE_STEP_KEY"
  echo "docker tag $from $to:latest"
  docker tag "$from" "$to:latest"
fi

if [ "$LOG_DOCKER" == "true" ]; then
  echo "docker logs..."
  docker-compose logs --tail 2000
  cat ./*.logs || true
fi

if [ "$IS_COMPOSE_RUNNER" = "true" ] && [ "$BUILDKITE_COMMAND_EXIT_STATUS" = "1" ]; then
  echo "shutting down docker"
  docker-compose down --volumes || true
fi

if [ "$DOCKER_CLEAN" == "true" ] || { [ "$BUILDKITE_COMMAND_EXIT_STATUS" = "1" ] && [ "$DOCKER_CLEAN_ON_FAIL" = "1" ]; }; then
  ./dishctl.sh clean_docker_if_disk_full
fi

echo "bye"
