app = "dish-timescale"

kill_signal = "SIGINT"
kill_timeout = 5

[mount]
source="timescale_data"
destination="/var/lib/postgresql/data"

[experimental]
private_network = true

[[services]]
  internal_port = 5432
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "10s"
    port = "5432"
    restart_limit = 2
    timeout = "6s"
