app = "dish-redis"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  private_network = true

[mounts]
source      = "redis_server"
destination = "/data"

[[services]]
  internal_port = 6379
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 10000
    soft_limit = 9000

  [[services.ports]]
    handlers = []
    port = "10000"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "10s"
    port = "8080"
    restart_limit = 5
    timeout = "2s"
