# fly.toml file generated for dish-redis on 2021-03-09T08:18:36-07:00

app = "dish-redis"

kill_signal = "SIGINT"
kill_timeout = 5

[mounts]
source      = "redis_server"
destination = "/data"

[[services]]
  internal_port = 6379
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = []
    port = "10000"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "10s"
    port = "8080"
    restart_limit = 5
    timeout = "2s"
