// Generated by dts-bundle-generator v5.9.0

/// <reference types="estree" />
/// <reference types="json-schema" />
/// <reference types="node" />

import Webpack from 'webpack';

export declare function createWebpackConfig({ entry, env, target, cwd, babelInclude, tamaguiOptions, disableHot, resolve, polyFillPath, htmlOptions, resetCache, defineOptions, noMinify, }: CreateWebpackConfig): Webpack.Configuration;
export default createWebpackConfig;

export {};
