#!/usr/bin/env bash
set -e pipefail

if [ "$TF_VAR_GOOGLE_SEARCH_PROXY" = "" ]; then
    echo "missing env"
    exit 1
fi

flyctl secrets set \
    DISH_ENV="staging" \
    HASURA_ENDPOINT="http://hasura:8080" \
    REDIS_HOST="dish-redis.internal" \
    REDIS_PORT="${FLY_REDIS_PORT}" \
    REDIS_PASSWORD="${FLY_REDIS_PASSWORD}" \
    PGHOST="postgres" \
    PGPASSWORD="postgres" \
    HASURA_SECRET="${TF_VAR_HASURA_GRAPHQL_ADMIN_SECRET:-password}" \
    TIMESCALE_HOST="$TIMESCALE_FLY_POSTGRES_HOST" \
    TIMESCALE_USER="$TIMESCALE_FLY_POSTGRES_USER" \
    TIMESCALE_PASSWORD="$TIMESCALE_FLY_POSTGRES_PASS" \
    TIMESCALE_PORT="$TIMESCALE_FLY_POSTGRES_PORT" \
    TIMESCALE_DB="$TIMESCALE_FLY_POSTGRES_DB" \
    UBEREATS_PROXY="${TF_VAR_UBEREATS_PROXY}" \
    HEREMAPS_API_TOKEN="${TF_VAR_HEREMAPS_API_TOKEN}" \
    INFATUATED_PROXY="${TF_VAR_INFATUATED_PROXY}" \
    MICHELIN_PROXY="${TF_VAR_MICHELIN_PROXY}" \
    YELP_AWS_PROXY="${TF_VAR_YELP_AWS_PROXY}" \
    TRIPADVISOR_PROXY="${TF_VAR_TRIPADVISOR_PROXY}" \
    GOOGLE_SEARCH_PROXY="${TF_VAR_GOOGLE_SEARCH_PROXY}" \
    GOOGLE_AWS_PROXY="${TF_VAR_GOOGLE_AWS_PROXY}" \
    GOOGLE_USERCONTENT_AWS_PROXY="${TF_VAR_GOOGLE_USERCONTENT_AWS_PROXY}" \
    DOORDASH_GRAPHQL_AWS_PROXY="${TF_VAR_DOORDASH_GRAPHQL_AWS_PROXY}" \
    GRUBHUB_AWS_PROXY="${TF_VAR_GRUBHUB_AWS_PROXY}" \
    YELP_CDN_AWS_PROXY="${TF_VAR_YELP_CDN_AWS_PROXY}" \
    LUMINATI_PROXY_HOST="${TF_VAR_LUMINATI_PROXY_HOST}" \
    LUMINATI_PROXY_PORT="${TF_VAR_LUMINATI_PROXY_PORT}" \
    LUMINATI_PROXY_DATACENTRE_USER="${TF_VAR_LUMINATI_PROXY_DATACENTRE_USER}" \
    LUMINATI_PROXY_DATACENTRE_PASSWORD="${TF_VAR_LUMINATI_PROXY_DATACENTRE_PASSWORD}" \
    LUMINATI_PROXY_RESIDENTIAL_USER="${TF_VAR_LUMINATI_PROXY_RESIDENTIAL_USER}" \
    LUMINATI_PROXY_RESIDENTIAL_PASSWORD="${TF_VAR_LUMINATI_PROXY_RESIDENTIAL_PASSWORD}" \
    DO_SPACES_ID="${TF_VAR_DO_SPACES_ID}" \
    DO_SPACES_SECRET="${TF_VAR_DO_SPACES_SECRET}" \
    GPT3_KEY="${TF_VAR_GPT3_KEY}" \
    NODE_OPTIONS="--max_old_space_size=5120" \
    GORSE_ENDPOINT="http://dish-gorse.internal" \
    DISH_DEBUG="1" \
    || true
