app = "dish-db"

kill_signal = "SIGTERM"
kill_timeout = 300

[env]
PRIMARY_REGION = "lax"

[checks.role]
type     = "script"
interval = 60000
timeout  = 10000
command  = "flycheck"
args     = [ "role" ]

[checks.pg]
type         = "script"
interval     = 30000
timeout      = 10000
grace_period = "10s"
command      = "flycheck"
args         = [ "pg" ]

[checks.vm]
type     = "script"
interval = 30000
timeout  = 10000
command  = "flycheck"
args     = [ "vm" ]

[experimental]
private_network = true
enable_consul   = true
auto_rollback   = false
metrics_port    = 9187
metrics_path    = "/metrics"

[mount]
source      = "dish_db"
destination = "/data"
