# Note that Github's web editor has linting for Github Action YAML
# And also there is a JSON schema for validating in your local editor:
# http://json.schemastore.org/github-workflow

name: Code Health
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISH_ENV: "test"
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'
    - name: Install dev dependencies
      run: .github/workflows/scripts/install_dev_deps.sh
    - name: Prettier linting
      run: .github/workflows/scripts/prettier.sh

