# Note that Github's web editor has linting for Github Action YAML
# And also there is a JSON schema for validating in your local editor:
# http://json.schemastore.org/github-workflow

name: Integration
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISH_ENV: "test"
      HASURA_ENDPOINT: "http://localhost:8080"
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'
    - name: Install dev dependencies
      run: .github/workflows/scripts/install_dev_deps.sh
    - name: Setup services
      run: .github/workflows/scripts/setup_services.sh
    - name: Build docker images
      run: .github/workflows/scripts/build.sh
    - name: Run integration tests
      run: .github/workflows/scripts/integration_tests.sh
    - name: 'On fail: Output container logs'
      run: .github/workflows/scripts/on_failure.sh
      if: failure()
